repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.11
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
# Removed automatic test execution to prevent workshop workflow interruptions
# Tests should be run manually with: uv run --group dev pytest